name: azoozii
favicon: null
layout_spectrum: 0.977162549039349
typography_spectrum: 0.5252723628655076
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.0986218168400228
  lightness: 0.20913900178857148
  saturation: 0.30838013207539916
  rhythmicContrast: 0.838374872226268
purpose: []
